In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

import networkx as nx
import random

In [2]:
import os
import sys
sys.path.insert(0, os.path.abspath('../../code/'))
from utils.causal_graphs import compute_egde_list, compute_graph_measures, compute_degree_features, compute_edge_features

In [3]:
import warrior as war

WARRIOR
   brain initialized
   network initialized


In [4]:
# N_NODES = 10
# N_EDGES = 25
# A = np.zeros((N_NODES, N_NODES), dtype=int)
# indices = random.sample(range(N_NODES * N_NODES), N_EDGES)
# print(indices)
# for index in indices:
#         row_index = index // N_NODES
#         col_index = index % N_NODES
#         A[row_index, col_index] = 1
# np.fill_diagonal(A, 0)
# A

In [5]:
causal_fcs = np.load('../local/causal_graphs/processed/causal_fcs.npy')
print(causal_fcs.shape)
filtered_fcs = np.load('../local/causal_graphs/processed/filtered_fcs.npy')
print(filtered_fcs.shape)

(426, 100, 100)
(426, 100, 100)


In [6]:
NODES = causal_fcs.shape[1]
EDGES = int((NODES*(NODES-1)) / 2)

In [7]:
cfc = causal_fcs[0]
fc = filtered_fcs[0]

In [8]:
in_degree = np.where(cfc==1,1,0).sum(axis=0)
out_degree = np.where(cfc==1,1,0).sum(axis=1)
degree = in_degree + out_degree

In [9]:
print(degree[:10])
print(in_degree[:10])
print(out_degree[:10])

[24 23 21 14 21 26 23 30 26 19]
[11 13 16  6  4  6 16 14  9 11]
[13 10  5  8 17 20  7 16 17  8]


In [10]:
edge_list, nx_edge_list = compute_egde_list(fc)
print(edge_list.shape)
print(edge_list[:,:6])
print(len(nx_edge_list))
print(nx_edge_list[:6])

(1377, 2)
[[ 0  1]
 [ 0 19]
 [ 0 34]
 ...
 [99 89]
 [99 93]
 [99 95]]
1377
[(0, 1), (0, 19), (0, 34), (0, 48), (0, 50), (0, 55)]


In [11]:
G = nx.DiGraph()
G.add_edges_from(nx_edge_list)
print(f'Directed: {nx.is_directed(G)}')
print(f'Nodes: {G.number_of_nodes()}')
print(f'Edges: {G.number_of_edges()}')
print(f'Density: {G.number_of_edges() / EDGES:.2f}')

Directed: True
Nodes: 100
Edges: 1377
Density: 0.28


In [23]:
measures = compute_graph_measures(nx_edge_list) # IN_CENTRALITY, OUT_CENTRALITY, CLUSTERING
print(measures.shape)
measures[:5,:]

(100, 3)


array([[0.0906847 , 0.09987363, 0.13949275],
       [0.0774473 , 0.07121974, 0.1541502 ],
       [0.11857127, 0.0291137 , 0.16666667],
       [0.02791352, 0.0544754 , 0.0989011 ],
       [0.03198196, 0.13843329, 0.16666667]])

In [21]:
# STRENGHT, DEGREE, P_STRENGHT, P_DEGREE, N_STRENGHT, N_DEGREE,
measures = compute_degree_features(fc) # 
print(measures.shape)
np.round(measures[:5,:],3)

(100, 6)


array([[13.   ,  8.   ,  5.   ,  2.368,  2.918, -0.551],
       [10.   ,  4.   ,  6.   , -0.139,  0.822, -0.961],
       [ 5.   ,  3.   ,  2.   ,  1.624,  1.979, -0.355],
       [ 8.   ,  1.   ,  7.   , -0.768,  0.291, -1.059],
       [17.   ,  7.   , 10.   ,  0.618,  2.415, -1.797]])

In [26]:
# CORRELATION VALUE
measures = compute_edge_features(fc, nx_edge_list) 
print(measures.shape)
np.round(measures[:10],3)

(1377,)


array([-0.158,  0.421, -0.056,  0.552,  0.565,  0.118,  0.139,  0.418,
       -0.174, -0.115])